version = 0.1

[default.deploy.parameters]
stack_name = "aws-ddd-api-development"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

[production.deploy.parameters]
stack_name = "aws-ddd-api-production"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false